class dict:
    __btl_value = __btl_mapping__()

    def __init__(self, value):
        if isinstance(value, dict):
            self.__btl_value = value.__btl_value
        else:
            self.__btl_value = value

    def __getitem__(self, key):
        return self.__btl_value[key]

    def __setitem__(self, key, value):
        self.__btl_value[key] = value

    def __bool__(self):
        return 0 < len(self.__btl_value)
